### PR TITLE
fix: prevent newline processing in output

### LINKED ISSUE #15: a '\n' are executing instead readit causing SC2034 ERROR
Correct Code (Passed in ShellCheck)
`MyBalR=$(echo "$MyBal" | awk '{printf("%d\n",$1 + 0.5)}')`

Get this on action-sh-checker v0.1.5 (and4 too) (are doing the \n on checking instead read it)
````
MyBalR=$(echo "$MyBal" | awk '{printf("%d
",$1 + 0.5)}')
^----^ SC2034: MyBalR appears unused. Verify use (or export if used externally).
````

### PR DESCRIPTION
**Pull request by tgallacher**
Fixes #15 

Problem arises due to the command expansion, `$(...)`. 

Output should match that if using `shellcheck` directly.

Confirmed using bash v5

### CODE REVIEW

File: entrypoint.sh [hunk 1]
```diff
@@ -84,7 +84,7 @@ exit_code=0
 if [ "$SHELLCHECK_DISABLE" != "1" ]; then
 	echo -e "Validating shell scripts files using shellcheck\n"
 	# shellcheck disable=SC2086
-	shellcheck_error="$(shellcheck $sh_files)"
+	shellcheck_error="$(cat <(shellcheck $sh_files))"
 	shellcheck_code="$?"
```
Comment (luizm) [inline entrypoint.sh:88]: This exit code still working?

**Comment by luizm** [comment]
Wow.. thank you :)

File: entrypoint.sh (hunk 1 above)
Comment (tgallacher) [reply entrypoint.sh:88]: ah, good point. It won't. Let me take a look

Comment (tgallacher) [reply entrypoint.sh:88]: Done.

I don't think the `while read -r` will be fully POSIX compliant but as long as this action runs it within a bash script you should be good.

Conformed both on bash 5 (_I upgraded since my last push_)

Comment (luizm) [reply entrypoint.sh:88]: I didn't know about PIPESTATUS.. its made my day worth :)

Comment (luizm) [reply entrypoint.sh:88]: lets ship it

Comment (luizm) [reply entrypoint.sh:88]: https://github.com/luizm/action-sh-checker/releases/tag/v0.1.9

Thank you so much @tgallacher
